import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Home/Sheard/Navbar";
import Footer from "@/Components/Home/Sheard/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HomeCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="md:max-w-11/12 mx-3 md:mx-auto my-5">
          <Navbar></Navbar>
        </header>
        <main className="md:max-w-11/12 mx-3 md:mx-auto mb-5 min-h-[calc(100vh-244px)]">
          {children}
        </main>
        <footer className="">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
