import React from "react";
import ServicesCard from "@/Components/Card/ServicesCard";
import { getServices } from "../action/server/service";
export const metadata = {
  title: "All Service",
  description: "Generated by create next app",
};
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const Services = async () => {
  await wait(1000);
  const servicecData = await getServices();
  return (
    <div className="p-4 md:p-0">
      <h1 className="text-3xl font-bold text-primary my-6 md:my-15 text-center">
        Our
        <span className="text-secondary"> Services</span>
      </h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {servicecData.map((service) => (
          <ServicesCard service={service} key={service._id}></ServicesCard>
        ))}
      </div>
    </div>
  );
};

export default Services;
